name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main

env:
    NODE_VERSION: 18

jobs:
    deploy:
        name: Deploying
        runs-on: ubuntu-latest
        steps:
            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Code Checkout
              uses: actions/checkout@v4

            - name: Install Dependencies
              run: npm i

            - name: Run Build
              run: npm run build

            - name: Deploy to GitHub Pages
              uses: crazy-max/ghaction-github-pages@v4
              with:
                  target_branch: gh-pages
                  build_dir: build
              env:
                  GH_PAT: ${{ secrets.GH_PAT }}
